<footer class="footer fixed-bottom bg-dark p-2">
    <div class="row">
        <div class="col-2 offset-1">
            <a href="https://www.instagram.com/wraaksaus/"><i class="fab fa-instagram footLink"></i></a>
        </div>
        <div class="col-2 offset-1">
            <a href="https://www.instagram.com/wraaksaus/"><i class="fab fa-facebook-f footLink"></i></a>
        </div>
        <div class="col-2 offset-1">
            <a href="https://www.instagram.com/wraaksaus/"><i class="fab fa-youtube footLink"></i></a>
        </div>
        <div class="col-2 offset-1">
            <a href="https://soundcloud.com/user-508800509"><i class="fab fa-soundcloud footLink"></i></a>
        </div>
      </div>
    </footer>
    <script src="../../library/jquery/jquery.min.js"></script>
    <script src="../../library/bootstrap/js/bootstrap.min.js"></script>
    <script src="../../public/js/script.js"></script>
</body>