<!doctype html>
    <head>
        <title> W R A A K S A U S </title>
        <meta charset="utf-8">       
        <meta content='maximum-scale=1.0, initial-scale=1.0, width=device-width' name='viewport'>
        <link rel="stylesheet" href="../../library/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" href="../../public/css/styles.css">
        <script src="../../library/jquery/jquery.min.js"></script>
    <script src="../../library/bootstrap/js/bootstrap.min.js"></script>
    </head>

