<nav class="navbar navbar-expand-md navbar">
    <h6 class="float-left">Wraaksaus<h6>
    <!-- Dropdown toggler for small devices -->
    <button class="navbar-toggler ml-auto mr-auto" type="button" data-toggle="collapse" data-target="#navbar" >
        <span class="fas fa-bars text-white"></span>
    </button>
    <!-- Links -->
    <div class="navbar-collapse collapse justify-content-end" id="navbar">
        <a class="nav-item nav-link text-white link" href="/home">Home</a>
        <a class="nav-item nav-link text-white link" href="/over-pmt">Over ons</a>
        <a class="nav-item nav-link text-white link" href="/tool">Agenda</a>
        <a class="nav-item nav-link text-white link" href="/contact">Muziek</a>
        <a class="nav-item nav-link text-white link" href="/documentatie">Contact</a>
    </div>  	
</nav>